version: "3.8"
name: ${COMPOSE_PROJECT_NAME}
services:
  mysql80:
    platform: linux/arm64
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
